source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FlappyDog' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for USAMI
	rn_path = '../node_modules/react-native'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/Yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'BatchedBridge',
    'RCTNetwork',
    'RCTWebSocket'
  ]
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
          target.remove_from_project
    end
  end
end